this script can run at anywhere now

diff --git a/init/install b/init/install
--- a/init/install
+++ b/init/install
@@ -1,4 +1,7 @@
 #!/bin/bash
+SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")")"
+cd "$SCRIPTDIR"
+
 case $(uname) in
     Darwin)
         OS="Darwin"
@@ -22,8 +25,8 @@ read -p "Set proxy?(ie http_proxy https_proxy)[Y/n] " setProxy
 read -p "Set git? [Y/n] " setGit
 read -p "Set docker? [Y/n] " setDocker
 read -p "Set golang? [Y/n] " setGolang
-read -p "Set shell? [Y/n] " setShell
-read -p "Set service? [Y/n] " setService
+read -p "Set shell? [Y/n] (install zsh,zsh theme,source .custom-shell) " setShell
+read -p "Set service? [Y/n] (support archlinux rc-local service currently)" setService
 read -p "Set supervim? [Y/n] " setSupervim
 ##Install dev tools
 if [[ "$installDev"!=[nN] ]];then
@@ -49,12 +52,13 @@ fi
 
 ##Set proxy
 if [[ "$setProxy"!=[nN] ]];then
-    echo "Set proxy..."
-    if [ ! -e /usr/local/bin/ss-client ];then
-        echo "Error: Can't find ss-client!"
-        exit 1
-    fi
-    sudo /usr/local/bin/ss-client globalRestart
+    # echo "Set proxy..."
+    # if [ ! -e /usr/local/bin/ss-client ];then
+    #     echo "Error: Can't find ss-client!"
+    #     exit 1
+    # fi
+    # sudo /usr/local/bin/ss-client globalRestart
+    ssclient-go globalRestart
     if netstat -tan |grep -q 8118;then
         export http_proxy=127.0.0.1:8118
         export HTTP_PROXY=127.0.0.1:8118
@@ -126,7 +130,7 @@ if [[ "$setSupervim"!=[nN] ]];then
     cd supervim
     case "$OS" in
         Arch|Darwin)
-	    /bin/bash install.sh install nvim
+            /bin/bash install.sh install nvim
             ;;
         *)
             /bin/bash install.sh install vim
