add kcptun install script

diff --git a/ss-go/optimize/kcptun/kcptun b/ss-go/optimize/kcptun/kcptun
--- a/ss-go/optimize/kcptun/kcptun
+++ b/ss-go/optimize/kcptun/kcptun
@@ -1,14 +1,12 @@
 #!/bin/bash
-. /etc/init.d/functions
-
-ROOT=/ss-go
+ROOT=/kcptun
 cd "$ROOT"
-prgname=$(ls shadowsocks-server*)
-echo "shadowsocks app name is: $prgname"
+prgname=$(ls server_linux*)
+echo "kcptun app name is: $ROOT/$prgname"
+echo "kcptun config file is :$ROOT/config.json"
 start(){
-    ulimit -n 51200
     if [ -z "$prgname" ];then
-        echo "shadowsocks-server not found in $ROOT">&2 
+        echo "kcptun server not found in $ROOT">&2 
         exit 1
     fi
     if ps aux | grep -v grep | grep  ${prgname};then
