max_server

diff --git a/ss-go/core/ss-go b/ss-go/core/ss-go
--- a/ss-go/core/ss-go
+++ b/ss-go/core/ss-go
@@ -14,6 +14,7 @@ echo "shadowsocks config file is: $ROOT/config.json"
 echo "---------------------------------------------------------------"
 
 start(){
+    oneStop
     ulimit -n 51200
     if [ -z "$prgname" ];then
         echo "shadowsocks-server not found in $ROOT">&2 
@@ -35,6 +36,44 @@ start(){
         # echo "Failed: ${prgname} start failed!"
     # fi
     fwOn
+}
+
+oneStart(){
+    stop
+    ulimit -n 51200
+    prgname=$(ls max_server*)
+    if [ -z "$prgname" ];then
+        echo "shadowsocks-server not found in $ROOT">&2 
+        exit 1
+    fi
+    if ps aux | grep -v grep | grep -q  ${prgname};then
+        echo "Warning: ${prgname} is already running"
+        exit 1
+    fi
+    ./${prgname} > /dev/null  2>&1 &
+    if pgrep "${prgname:0:15}">/dev/null 2>&1;then
+        echo "OK: ${prgname} has started."
+    else
+        echo "Failed: ${prgname} start failed!"
+    fi
+    # if ps aux | grep -v grep | grep -q  ${prgname};then
+        # echo "OK: ${prgname} has started"
+    # else
+        # echo "Failed: ${prgname} start failed!"
+    # fi
+    fwOn
+
+}
+
+oneStop(){
+    prgname=$(ls max_server*)
+    if pgrep "${prgname:0:15}";then
+        pkill "${prgname:0:15}"
+        status
+    else
+        echo "**Warning**${prgname} is not running!"
+    fi
+    fwOff
 }
 
 stop(){
@@ -88,7 +127,7 @@ config(){
 }
 
 usage(){
-    echo "Usage: $0 {start|stop|status|restart|config|fwOn|fwOff|uninstall}">&2
+    echo "Usage: $0 {start|stop|status|restart|config|fwOn|fwOff|uninstall|oneStart|oneStop}">&2
     echo "        fwOn  for firewall on"
     echo "        fwOff for firewall off"
     echo "        config for port setting"
@@ -199,6 +238,12 @@ case "$1" in
         ;;
     uninstall)
         uninstall
+        ;;
+    oneStart)
+        oneStart
+        ;;
+    oneStop)
+        oneStop
         ;;
     *)
         usage
